name: mysql
on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - name: Setup mysql
              uses: mirromutth/mysql-action@master

              with: 
                mysql version: '8.0'
                mysql database: 'startcode_test' 
                mysql user: ${{ secrets.DB_USER }} 
                mysql password: ${{ secrets.DB_PASSWORD }}